# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*github-script*"
  # Updates for Gradle dependencies used in the app
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 200
    reviewers:
      - "vector-im/element-android-reviewers"
    ignore:
      - dependency-name: com.google.zxing:core
  - package-ecosystem: docker
    directory: "./"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "./jenkins/adb-connector"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "./jenkins/agent"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "./jenkins/controller"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "./jenkins/qodana"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
