tasks:
  - init: |
      docker volume create --driver local \
        --opt type=none \
        --opt device=/workspace/MyFirstAndroidAppBuiltByJenkins \
        --opt o=bind qodana-data
      docker-compose -f jenkins/gitpod-docker-compose.yml pull
  - command: |
      docker-compose -f jenkins/gitpod-docker-compose.yml up


ports:
  - port: 50000
    onOpen: ignore
  - port: 8080
    onOpen: open-browser

vscode:
  extensions:
    - ms-azuretools.vscode-docker