tasks:
  - init: |
      docker-compose -f jenkins/docker-compose.yml pull
  - command: |
      docker-compose -f jenkins/docker-compose.yml up


ports:
  - port: 50000
    onOpen: ignore
  - port: 8080
    onOpen: open-browser

vscode:
  extensions:
    - ms-azuretools.vscode-docker