def getBranchName() {
   return "${GIT_BRANCH.split('/').size() > 1 ? GIT_BRANCH.split('/')[1..-1].join('/') : GIT_BRANCH}"
}

def getSimplifiedBranchName() {
   return "${getBranchName().replace('/', '-')}"
}

pipeline {
    triggers { cron('0 10 * * *') }
    environment {
        BRANCH_NAME = getSimplifiedBranchName()
    }
    agent any
    options {
        timestamps()
    }
    stages {
        stage('Updating the plugin list to the latest available versions') {
            agent any
            steps {
                script {
                    pluginsAreUpToDate = sh (
                        script: 'bash -x jenkins/controller/update-plugins.sh',
                        returnStdout: true
                    )
                }
            }
        }
    }
}
