#  docker compose up -d --build --force-recreate
services:
  jenkins:
    build: ./controller
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home:rw
      - ./casc.d:/var/jenkins_home/casc.d/:ro
      # Mounting the ssh private key as "container secret" makes it available in JCasc as the variable ${SSH_AGENT_KEY}
      - ./secrets/id_jenkins.pem:/run/secrets/SSH_AGENT_KEY:ro
      #- ./secrets/converted-github-app.pem:GITHUB_APP_KEY:ro
    environment:
      - JENKINS_EXT_URL=http://localhost:8080
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.d/
      - GITHUB_APP_ID
      - GITHUB_APP_KEY
      - ANDROID_PUBLISHER_CREDENTIALS
      - org.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true
      - PUBLIC_IP
      - STF_API_TOKEN
      - STF_HOST_NAME
      # - JENKINS_OPTS=-Djenkins.install.runSetupWizard=false
  jenkins-agent:
    platform: linux/amd64
    build: ./agent
    restart: unless-stopped
    privileged: true
    volumes:
      - jenkins-agent-data:/home/jenkins:rw
      - qodana-data:/home/jenkins/qodana:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBpNqXQ4x7fPPUBbYPxKF77Zqq6d35iPCD2chg644OUD noone@localhost.local
  android-agent:
    platform: linux/amd64
    build: ../
    restart: unless-stopped
    volumes:
      - android-agent-data:/home/jenkins:rw
      - ../adbkey.pub:/home/jenkins/.android/adbkey.pub:rw
      - ../adbkey.txt:/home/jenkins/.android/adbkey:rw
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBpNqXQ4x7fPPUBbYPxKF77Zqq6d35iPCD2chg644OUD
      - STF_HOST_NAME
volumes:
  qodana-data:
  jenkins-data:
  jenkins-agent-data:
  android-agent-data:
  rethinkdb-data:
